Issue85 metadata api
hyperledger/firefly-tokens-erc1155 pull request #87
Opened 2022-08-12 10:13 UTC by Chengxuan

Resolves #85 

- Checked in ABI json from ERC1155
- updated token service to use the metadata driven API
- introduced a new env var CONTRACT_ADDRESS with migration logic if it's not set

2022-08-12 17:59 UTC, awrichar reviewed
Reviewing this now - two style/formatting notes:
* Can you run `npm run format`?
* Not sure why the entire samples/solidity/package-lock.json file was rewritten - looks like a bunch of whitespace changed for some reason. Would be nice to not overwrite it if it's not needed.

2022-08-12 18:01 UTC, awrichar commented on src/tokens/tokens.service.ts
> +    if (!this.contractAddress) {
`init()` is not guaranteed to be called on every start (only has to be called once ever). So we need to be sure `this.contractAddress` is initialized somewhere else. Might want to do it lazily the first time a query/transaction happens?

2022-08-12 18:02 UTC, awrichar commented on src/tokens/tokens.service.ts
> +    if (!this.contractAddress) {
Come to think of it, there's probably an existing bug with the initialization of `this.supportsCustomUri` above as well.

2022-08-12 18:09 UTC, awrichar requested changes
Just one functional change needed surrounding init. Otherwise looks great!

2022-08-12 19:37 UTC, Chengxuan commented
@awrichar thank you for the comments. I've addressed them. Ready to be reviewed again.

2022-08-15 16:13 UTC, awrichar commented on src/tokens/tokens.service.ts
> +      this.logger.debug(`s: ${this.contractAddress}`);
Could annotate this log a little better (or remove if it's not needed now)

2022-08-15 16:15 UTC, awrichar approved these changes

2022-08-15 16:16 UTC, merged

2022-08-15 16:25 UTC, Chengxuan reviewed
debug log remove in https://github.com/hyperledger/firefly-tokens-erc1155/pull/91